CastleApps/CastleApps/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apartments.urls')),
    path('users/',include('users.urls')),
]

CastleApps/apartments/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='frontpage'),
    path('agents/',views.agents, name='agents'),
    path('all-apartments/',
         views.all_apartments, name="apartment-list"),
    path('apartments/<int:apartmentid>/',
         views.singleApartment, name="apartment"),
    path('create_apartment', views.create_apartment, name="create-apartment"),
    path('create_location', views.create_location, name="create-location")

]

CastleApps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name="register"),
    path('login', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout')
]

CastleApps/apartments/models.py
from django.db import models

# Create your models here.
from django.db import models #Tells it to map to database
from django.utils import timezone
from django.conf import settings
from datetime import datetime

from django.shortcuts import  render

# You do not need to specify primary key. It is automatically
# generated and auto incremented

#Steps to update the Database
# makemigrations apartments
# migrate apartments
# sqlmigrate apartments 0001_initial
# migrate

# Our model.py was designed with the ID being auto generated in mind.

# Location is a general place to be able to better normalize the data.
class Locations(models.Model):
    city = models.CharField(max_length=100, default=None)
    region = models.CharField(max_length=50)
    zip = models.CharField(max_length=15)
    country = models.CharField(max_length=100)
    def __str__(self):
        return self.country

# Apartments is general information about the apartment that is only inserted once
class Apartments(models.Model):
    address = models.CharField(max_length = 50)
    size = models.IntegerField()
    rooms = models.IntegerField()
    bathrooms = models.IntegerField()
    type = models.CharField(max_length=50)
    timeOfConstruction = models.IntegerField( default = 2000)
    type = models.CharField(max_length = 50)
    displayImage = models.CharField(max_length = 5000)
    location = models.ForeignKey(Locations, on_delete=models.CASCADE, ) # Foreign keys are singular. While the table
    userID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)
    def __str__(self):
        self.displayImage, self.location

# Apartments usually have many images associated with them
class ApartmentImages(models.Model):
    image = models.CharField(max_length=5000)
    aID = models.ForeignKey(Apartments, on_delete=models.CASCADE)
    def __str__(self):
        return self.image


# Each apartments has a listing. It can have many listings.
# Same apartment can only have one listing up at a time though!
class Listings(models.Model):
    price = models.BigIntegerField()
    desc = models.TextField()
    registered = models.DateTimeField(default=timezone.now)
    soldOnDate = models.DateTimeField(default = None)
    openHouse = models.CharField(default = None, max_length = 75)
    agentID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    apartment = models.ForeignKey(Apartments, on_delete=models.CASCADE)


# Each apartment can have many documents attached to them. repair bills/copy of deed and more
class listingDocs(models.Model):
    listing = models.ForeignKey(Listings, on_delete = models.CASCADE)
    attachment = models.CharField(max_length = 500, default = None)
    description = models.CharField(max_length = 500, default = None)

# Used to calculate the final price and used to display the list on our website
class PriceLists(models.Model):
    salesCost = models.CharField(max_length = 20)
    appraisalCost = models.CharField(max_length = 15)
    photoCost = models.CharField(max_length = 15)
    managementCost = models.CharField(max_length = 15)
    dataCollection = models.CharField(max_length = 15)

# All the information necessary to make a purchase on our platform
class PaymentInfos(models.Model):
    cardNumber = models.CharField(max_length=30)
    cardHolder = models.CharField(max_length=80)
    expMonth = models.IntegerField()
    expYear = models.IntegerField()
    address = models.CharField(max_length=80)
    aptSuite = models.CharField(max_length=20, default = None)
    userID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete= models.CASCADE)

CastleApps/users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    phone = models.CharField(max_length = 20, blank = True, default = None, null = True)
    profileImagePath = models.CharField(blank = True, default = None, max_length = 50000, null = True)
    workplace = models.CharField(max_length=20, blank=True, default=None, null = True)
    def __str__(self):
        return self.email

CastleApps/apartments/forms/apartmentform.py
from django.forms import ModelForm, widgets
from ..models import Apartments, Locations
from django import forms


class CastleAppsCreateForm(ModelForm):
    class Meta:
        image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class' : 'form-control'}))
        model = Apartments
        exclude = [ 'pkid' ]
        widgets = {
            'RegNumber': widgets.TextInput(attrs={'class' : 'form-control'}),
            'Address': widgets.TextInput(attrs={'class': 'form-control'}),
            'Size': widgets.NumberInput(attrs={'class' : 'form-control'}),
            'Rooms': widgets.NumberInput(attrs={'class' : 'form-control'}),
            'Bathrooms': widgets.NumberInput(attrs={'class' : 'form-control'}),
            'Description': widgets.TextInput(attrs={'class': 'form-control'}),
            'timeOfConstruction': widgets.TextInput(attrs={'class': 'form-control'}),
            'type': widgets.TextInput(attrs={'class':'form-control'})
}

CastleApps/apartments/forms/locationform.py
from django.forms import ModelForm, widgets
from ..models import Locations
from django import forms


class AddressCreateForm(ModelForm):
    class Meta:
        model = Locations
        exclude = ['id']
        widgets = {
            'zip': widgets.TextInput(attrs={'class': 'form-control'}),
            'region': widgets.TextInput(attrs={'class': 'form-control'}),
            'city': widgets.TextInput(attrs={'class': 'form-control'}),
            'country': widgets.TextInput(attrs={'class': 'form-control'})
        }

CastleApps/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Users

class UsersCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = Users
        fields = ('username', 'email')

class UsersChangeForm(UserChangeForm):

    class Meta:
        model = Users
        fields = ('username', 'email')

CastleApps/apartments/views.py
from django.shortcuts import render,redirect
from .forms.apartmentform import CastleAppsCreateForm
from .forms.locationform import AddressCreateForm
#from .forms.signup_form import CastleAppsSignupForm
from django.http import HttpResponse
# Create your views here.
from apartments.models import *
from users.models import *
from django.db.models import Max




apartments = [
    {
        'aid': '123',
        'address': 'Lindarberg 26',
        'city': 'Hafnarfjörður',
        'zip': '221',
        'country': 'Iceland',
        'size': '250',
        'rooms': '6',
        'price': '50000000',
        'type': 'Villa',
        'image': '/static/img/b70.jpeg'
    },
    {
        'aid': '124',
        'address': 'Miðvangur 56',
        'city': 'Hafnarfjörður',
        'zip': '220',
        'country': 'Iceland',
        'size': '230',
        'rooms': '3',
        'price': '73000000',
        'type': 'Penthouse apartment',
        'image': '/static/img/b70.jpeg'
    },
    {
        'aid': '125',
        'address': 'Skuggagata 56',
        'city': 'Reykjavík',
        'zip': '101',
        'country': 'Iceland',
        'size': '500',
        'rooms': '10',
        'price': '12000000',
        'type': 'Penthouse apartment',
        'image': '/static/img/b70.jpeg'
    },
    {
        'aid': '126',
        'address': 'Bergstaðastræti 70',
        'city': 'Reykjavík',
        'zip': '101',
        'country': 'Iceland',
        'size': '100',
        'rooms': '2',
        'price': '150000000',
        'type': 'Luxury Lodge',
        'image': '/static/img/b70.jpeg'
    }
]

# This is the main home page
def home(request):
    context = {
        'apartments': Apartments.objects.all(),
    }
    return render(request, 'apartments/home.html', context)


# This is
def agents(request):

    users = Users.objects.filter(is_superuser = True)
    #print("PRINTING ALL THE USERS : ", users.profileImagePath)
    context = {
       'agents': users
    }
    return render(request, 'apartments/agents.html', context)

# This is the page you are led to when an apartment is clicked on
def singleApartment(request, apartmentID): # Need to add error handling
    context = {}
    print("ERROR HANDLING" ,apartmentID)
    if Apartments.objects.get(id=apartmentID).id == apartmentID:
        #print("HEre we are", apartmentid)
        apartments = Apartments.objects.get(id = apartmentID)
        apartmentImages = Apartments.objects.get(pk=apartmentID).apartmentimages_set.all()
        apartmentImages = apartmentImages.all()
        listings = Listings.objects.filter(apartment=apartmentID)
        print("LISTING OBJECT: ", listings)
        idOfActiveListing = listings.aggregate(Max('id'))
        listing = Listings.objects.get(id = idOfActiveListing['id__max'])
        print("PRINTING agentID: ", listing.agentID_id)
        listingAgent = Users.objects.get(id = listing.agentID_id)
        context = {
            'apartment': apartments,
            'images' : apartmentImages,
            'agent': listingAgent
        }
    return render(request, 'apartments/single-apartment.html', context)


# DISPLAY SINGLE Agent NExt implmentation Fridrik

def singleAgent(request, agentID):
    pass


def all_apartments(request):
    context = {
        'apartments': apartments
    }
    return render(request, 'apartments/apartments-list.html', context)

def create_location(request):
    if request.method == 'POST':
        address_form = AddressCreateForm(data=request.POST, prefix='location')
        if address_form.is_valid():
            address_form.save()
            return redirect('create-apartment')
        context = {'address_form': address_form}
        return render(request, 'apartments/create-location.html', context)
    else:
        address_form = AddressCreateForm(data=request.GET)
        return render(request, 'apartments/create-location.html', {
            'address_form': address_form
        })

def create_apartment(request):
    if request.method == 'POST':
        # Read data from apartments form, and from address form.
        app_form = CastleAppsCreateForm(data=request.POST, prefix='apartment')
        if app_form.is_valid():
            app_form = app_form.save()
            return redirect('frontpage')

        context = {'app_form': app_form}
        return render(request, 'apartments/create-apartment.html', context)
    else:
        app_form = CastleAppsCreateForm(data=request.GET)
        return render(request, 'apartments/create-apartment.html', {
            'app_form': app_form
        })

CastleApps/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    
    return render(request, 'user/register.html', {
        'form': UserCreationForm()
    })

CastleApps/templates/apartments/about.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% endblock css %}
{% block content %}
<div class="employees">
    <div class="container">
    {{ employees.startDate }}
        {% for employee in employees %}
        <div class="item">
            <div class = employeeDescriptions> {{ employee.user.firstName }}</div>
            <h3>{{employee.description}} {{employee.startDate}}</h3>
            <div class="meta">{{employee.user.firstName}} {{employee.user.lastName}} {{ employee.user.email }}</div>
            <div class="desc">
                <img class = employeePicture src =  " {{ employee.user.profileImagePath }}"/>
                <p>{{users.phone}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

CastleApps/templates/apartments/agents.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/agents.css' %}">
{% endblock css %}
{% block content %}
<div class="agents">
    <div class="container">
        <div class="agents-wrapper">
            {% for agent in agents %}
            <div class="agent">
                <div class="image">
                    <img src=" {{ agent.profileImagePath }}"/>
                </div>
                <div class="meta">
                    <h2>{{agent.first_name}} {{agent.last_name}}</h2>
                    <div class="start"><span>Started working on {{agent.startDate}}</span></div>
                    <div class="contact">
                        <div class="email">Email: {{agent.email}}</div>
                        <div class="phone">Phone: {{agent.phone}}</div>
                    </div>
                    <div class="desc">
                        <p>{{agent.description}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

CastleApps/templates/apartments/apartments-list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/apartments.css' %}">
{% endblock css %}
{% block banner %}
{% endblock %}
{% block content %}
<div class="apartments">
    <div class="container">
        <div class="apartments-wrapper flexed">
            {% for apartment in apartments %}
            <div class="apartment">
                <div class="image">
                    <a href="/apartment/{{apartment.aid}}">
                        <img src="{{ apartment.image }}" alt="" srcset="">
                    </a>
                </div>
                <div class="meta">
                    <div class="address">
                        {{apartment.address}}
                    </div>
                    <div class="postdata">
                        {{apartment.zip}}, {{apartment.city}}
                    </div>
                    <div class="size">
                        {{apartment.size}} fm.
                    </div>
                    <div class="price">
                        {{apartment.price}} isk.
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
{% endblock%}

CastleApps/templates/apartments/create-apartment.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form action="{% url 'create-apartment' %}" class="background-white" method="POST">
            {% csrf_token %}
             {% for item in app_form %}
                <div class="form-group">
                    <label>{{item.name}}</label>
                    {{item}}
                </div>
            {% endfor %}

            <input type="submit" value="Create" class="btn btn-primary pull-right" style="clear:both; margin : 10px 0" />
        </form>

    </div>


{% endblock %}

CastleApps/templates/apartments/create-location.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
         <form action="{% url 'create-location' %}" class="background-white" method="POST">
             {% csrf_token %}
                {% for item in address_form %}
                 <div class="form-group">
                     <label>{{item.name}}</label>
                    {{item}}
                </div>
            {% endfor %}
          <input type="submit" value="Create" class="btn btn-primary pull-right" style="clear:both; margin : 10px 0" />
        </form>
    </div>


{% endblock %}

CastleApps/templates/apartments/home.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="{% static '/css/apartments.css' %}">
<link rel="stylesheet" href="{% static '/css/banner.css' %}">
{% endblock css %}
{% block banner %}
<div class="frontpage-banner">
    <div class="search-form">
        <form action="/">
            <div class="form-group">
                <label for="search">Search here</label>
                <input type="search" name="search" id="search">
            </div>
            <button type="submit">search</button>
        </form>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="apartments">
    <div class="container">
        <h2>Open houses</h2>
        <div class="apartments-wrapper slider owl-carousel">
            {% for apartment in apartments %}
            <div class="apartment">
                <div class="image">
                    <a href="/apartments/{{apartment.id}}">

                        <img src="{{ apartment.displayImage }}" alt="Image here" srcset="">
                    </a>
                </div>
                <div class="meta">
                    <div class="address">
                        {{apartment.address}}
                    </div>
                    <div class="postdata">
                        {{apartment.location.zip}}
                        {{apartment.location.city}} <br>
                        {{apartment.location.country}}
                    </div>
                    <div class="size">
                        {{apartment.size}} m2.
                    </div>
                    <div class="price">
                        $ {{apartment.listings_set.price}} .
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<script src="{% static '/js/sliders.js' %}"></script>
{% endblock%}

CastleApps/templates/apartments/single-apartment.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/apartments.css' %}">
{% endblock css %}
{% block content%}
<div class="container">
    <div class="apartment single">
        <div class="image">
            <img src="{{apartment.image}}" alt="">
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="location">
                    <h2>{{apartment.address}}</h2>
                    <p>{{apartment.zip}}</p>
                    <p>{{apartment.city}}</p>
                    <p>{{apartment.country}}</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="meta">
                    <p>{{apartment.type}} in {{apartment.location.region}}, {{apartment.location.city}}  </p>
                    <p>price: {{listing.price}}</p>
                    <p>Sold on the date: {{listing.price}}</p>

                 Agent: <img src="{{ agent.profileImagePath}}" alt="Image here" srcset="">
                    <p>AgentUserName: {{agent.username}}</p>
                    <p>Size: {{apartment.size}}</p>
                    <p>Rooms: {{apartment.rooms}}</p>
                    <p>Bathrooms: {{apartment.bathrooms}}</p>
                    <p>Constructed: {{apartment.timeOfConstruction}}</p>
                    <p>Registered: {{apartment.timeOfRegistration}}</p>
                    <p>Country: {{apartment.location.country}}</p>
                    <p>Zip: {{apartment.location.zip}}</p>
                    {%  for image in images %}
                        <img src="{{ image }}" alt="Image here" srcset="">
                    {%  endfor %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}